inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/riboseinc/oss-guides/main/ci/rubocop.yml

plugins:
- rubocop-performance
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'lib/suma/cli/reformat.rb'
    - 'lib/suma/cli/generate_schemas.rb'
    - 'lib/suma/cli/validate_ascii.rb'
    - 'lib/suma/cli/validate_links.rb'
    - 'lib/suma/cli/extract_terms.rb'
    - 'vendor/**/*'
